/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedFirmCommandRouteImport } from './routes/_authed.firm-command'
import { Route as AuthedHomeRouteImport } from './routes/_authed.home'
import { Route as AuthedRedTeamerRouteImport } from './routes/_authed.red-teamer'
import { Route as AuthedSearchRouteImport } from './routes/_authed.search'
import { Route as AuthedTrackerRouteImport } from './routes/_authed.tracker'
import { Route as AuthedWorkbenchRouteImport } from './routes/_authed.workbench'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFirmCommandRoute = AuthedFirmCommandRouteImport.update({
  id: '/firm-command',
  path: '/firm-command',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRedTeamerRoute = AuthedRedTeamerRouteImport.update({
  id: '/red-teamer',
  path: '/red-teamer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrackerRoute = AuthedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkbenchRoute = AuthedWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/signin': typeof SigninRoute
  '/firm-command': typeof AuthedFirmCommandRoute
  '/home': typeof AuthedHomeRoute
  '/red-teamer': typeof AuthedRedTeamerRoute
  '/search': typeof AuthedSearchRoute
  '/tracker': typeof AuthedTrackerRoute
  '/workbench': typeof AuthedWorkbenchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/signin': typeof SigninRoute
  '/firm-command': typeof AuthedFirmCommandRoute
  '/home': typeof AuthedHomeRoute
  '/red-teamer': typeof AuthedRedTeamerRoute
  '/search': typeof AuthedSearchRoute
  '/tracker': typeof AuthedTrackerRoute
  '/workbench': typeof AuthedWorkbenchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/signin': typeof SigninRoute
  '/_authed/firm-command': typeof AuthedFirmCommandRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/red-teamer': typeof AuthedRedTeamerRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/tracker': typeof AuthedTrackerRoute
  '/_authed/workbench': typeof AuthedWorkbenchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/signin'
    | '/firm-command'
    | '/home'
    | '/red-teamer'
    | '/search'
    | '/tracker'
    | '/workbench'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/signin'
    | '/firm-command'
    | '/home'
    | '/red-teamer'
    | '/search'
    | '/tracker'
    | '/workbench'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accept-invite'
    | '/signin'
    | '/_authed/firm-command'
    | '/_authed/home'
    | '/_authed/red-teamer'
    | '/_authed/search'
    | '/_authed/tracker'
    | '/_authed/workbench'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/firm-command': {
      id: '/_authed/firm-command'
      path: '/firm-command'
      fullPath: '/firm-command'
      preLoaderRoute: typeof AuthedFirmCommandRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/red-teamer': {
      id: '/_authed/red-teamer'
      path: '/red-teamer'
      fullPath: '/red-teamer'
      preLoaderRoute: typeof AuthedRedTeamerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tracker': {
      id: '/_authed/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthedTrackerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workbench': {
      id: '/_authed/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof AuthedWorkbenchRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedFirmCommandRoute: typeof AuthedFirmCommandRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedRedTeamerRoute: typeof AuthedRedTeamerRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedTrackerRoute: typeof AuthedTrackerRoute
  AuthedWorkbenchRoute: typeof AuthedWorkbenchRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFirmCommandRoute: AuthedFirmCommandRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedRedTeamerRoute: AuthedRedTeamerRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedTrackerRoute: AuthedTrackerRoute,
  AuthedWorkbenchRoute: AuthedWorkbenchRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
