/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedChannelsRouteImport } from './routes/_authed.channels'
import { Route as AuthedChatsRouteImport } from './routes/_authed.chats'
import { Route as AuthedContactsRouteImport } from './routes/_authed.contacts'
import { Route as AuthedFirmCommandRouteImport } from './routes/_authed.firm-command'
import { Route as AuthedHomeRouteImport } from './routes/_authed.home'
import { Route as AuthedPinsRouteImport } from './routes/_authed.pins'
import { Route as AuthedRedTeamerRouteImport } from './routes/_authed.red-teamer'
import { Route as AuthedSearchRouteImport } from './routes/_authed.search'
import { Route as AuthedThreadsRouteImport } from './routes/_authed.threads'
import { Route as AuthedTrackerRouteImport } from './routes/_authed.tracker'
import { Route as AuthedWorkbenchRouteImport } from './routes/_authed.workbench'
import { Route as AuthedThreadsThreadIdRouteImport } from './routes/_authed.threads.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChannelsRoute = AuthedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatsRoute = AuthedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsRoute = AuthedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFirmCommandRoute = AuthedFirmCommandRouteImport.update({
  id: '/firm-command',
  path: '/firm-command',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPinsRoute = AuthedPinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRedTeamerRoute = AuthedRedTeamerRouteImport.update({
  id: '/red-teamer',
  path: '/red-teamer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedThreadsRoute = AuthedThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrackerRoute = AuthedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkbenchRoute = AuthedWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedThreadsThreadIdRoute = AuthedThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AuthedThreadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/channels': typeof AuthedChannelsRoute
  '/chats': typeof AuthedChatsRoute
  '/contacts': typeof AuthedContactsRoute
  '/firm-command': typeof AuthedFirmCommandRoute
  '/home': typeof AuthedHomeRoute
  '/pins': typeof AuthedPinsRoute
  '/red-teamer': typeof AuthedRedTeamerRoute
  '/search': typeof AuthedSearchRoute
  '/threads': typeof AuthedThreadsRouteWithChildren
  '/tracker': typeof AuthedTrackerRoute
  '/workbench': typeof AuthedWorkbenchRoute
  '/threads/$threadId': typeof AuthedThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/channels': typeof AuthedChannelsRoute
  '/chats': typeof AuthedChatsRoute
  '/contacts': typeof AuthedContactsRoute
  '/firm-command': typeof AuthedFirmCommandRoute
  '/home': typeof AuthedHomeRoute
  '/pins': typeof AuthedPinsRoute
  '/red-teamer': typeof AuthedRedTeamerRoute
  '/search': typeof AuthedSearchRoute
  '/threads': typeof AuthedThreadsRouteWithChildren
  '/tracker': typeof AuthedTrackerRoute
  '/workbench': typeof AuthedWorkbenchRoute
  '/threads/$threadId': typeof AuthedThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/_authed/channels': typeof AuthedChannelsRoute
  '/_authed/chats': typeof AuthedChatsRoute
  '/_authed/contacts': typeof AuthedContactsRoute
  '/_authed/firm-command': typeof AuthedFirmCommandRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/pins': typeof AuthedPinsRoute
  '/_authed/red-teamer': typeof AuthedRedTeamerRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/threads': typeof AuthedThreadsRouteWithChildren
  '/_authed/tracker': typeof AuthedTrackerRoute
  '/_authed/workbench': typeof AuthedWorkbenchRoute
  '/_authed/threads/$threadId': typeof AuthedThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/onboarding'
    | '/signin'
    | '/channels'
    | '/chats'
    | '/contacts'
    | '/firm-command'
    | '/home'
    | '/pins'
    | '/red-teamer'
    | '/search'
    | '/threads'
    | '/tracker'
    | '/workbench'
    | '/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/onboarding'
    | '/signin'
    | '/channels'
    | '/chats'
    | '/contacts'
    | '/firm-command'
    | '/home'
    | '/pins'
    | '/red-teamer'
    | '/search'
    | '/threads'
    | '/tracker'
    | '/workbench'
    | '/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accept-invite'
    | '/onboarding'
    | '/signin'
    | '/_authed/channels'
    | '/_authed/chats'
    | '/_authed/contacts'
    | '/_authed/firm-command'
    | '/_authed/home'
    | '/_authed/pins'
    | '/_authed/red-teamer'
    | '/_authed/search'
    | '/_authed/threads'
    | '/_authed/tracker'
    | '/_authed/workbench'
    | '/_authed/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  OnboardingRoute: typeof OnboardingRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/channels': {
      id: '/_authed/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthedChannelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chats': {
      id: '/_authed/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthedChatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts': {
      id: '/_authed/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthedContactsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/firm-command': {
      id: '/_authed/firm-command'
      path: '/firm-command'
      fullPath: '/firm-command'
      preLoaderRoute: typeof AuthedFirmCommandRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pins': {
      id: '/_authed/pins'
      path: '/pins'
      fullPath: '/pins'
      preLoaderRoute: typeof AuthedPinsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/red-teamer': {
      id: '/_authed/red-teamer'
      path: '/red-teamer'
      fullPath: '/red-teamer'
      preLoaderRoute: typeof AuthedRedTeamerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/threads': {
      id: '/_authed/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AuthedThreadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tracker': {
      id: '/_authed/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthedTrackerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workbench': {
      id: '/_authed/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof AuthedWorkbenchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/threads/$threadId': {
      id: '/_authed/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AuthedThreadsThreadIdRouteImport
      parentRoute: typeof AuthedThreadsRoute
    }
  }
}

interface AuthedThreadsRouteChildren {
  AuthedThreadsThreadIdRoute: typeof AuthedThreadsThreadIdRoute
}

const AuthedThreadsRouteChildren: AuthedThreadsRouteChildren = {
  AuthedThreadsThreadIdRoute: AuthedThreadsThreadIdRoute,
}

const AuthedThreadsRouteWithChildren = AuthedThreadsRoute._addFileChildren(
  AuthedThreadsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChannelsRoute: typeof AuthedChannelsRoute
  AuthedChatsRoute: typeof AuthedChatsRoute
  AuthedContactsRoute: typeof AuthedContactsRoute
  AuthedFirmCommandRoute: typeof AuthedFirmCommandRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedPinsRoute: typeof AuthedPinsRoute
  AuthedRedTeamerRoute: typeof AuthedRedTeamerRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedThreadsRoute: typeof AuthedThreadsRouteWithChildren
  AuthedTrackerRoute: typeof AuthedTrackerRoute
  AuthedWorkbenchRoute: typeof AuthedWorkbenchRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChannelsRoute: AuthedChannelsRoute,
  AuthedChatsRoute: AuthedChatsRoute,
  AuthedContactsRoute: AuthedContactsRoute,
  AuthedFirmCommandRoute: AuthedFirmCommandRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedPinsRoute: AuthedPinsRoute,
  AuthedRedTeamerRoute: AuthedRedTeamerRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedThreadsRoute: AuthedThreadsRouteWithChildren,
  AuthedTrackerRoute: AuthedTrackerRoute,
  AuthedWorkbenchRoute: AuthedWorkbenchRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  OnboardingRoute: OnboardingRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
