import { Link } from "@tanstack/react-router";
import { Hash, MessageSquare, Plus, Send, Users, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { useChannels, useCreateDirectChannel, useCreatePin, useDeletePin, useMembers, useMessages, usePins, useSendMessage, useThreads, useCreateThread, useMarkChannelRead } from "@/lib/api/collaboration";

const RESOURCE_TYPES = ["CHANNEL", "MESSAGE", "THREAD", "ANALYSIS", "MATTER"] as const;
type Section = "pins" | "chats" | "channels" | "threads" | "contacts";

function State({ text, error = false }: { text: string; error?: boolean }) {
  return <div role={error ? "alert" : undefined} className={`rounded-xl border border-dashed p-8 text-center text-sm ${error ? "border-destructive/50 text-destructive" : "border-border text-muted-foreground"}`}>{text}</div>;
}

function MessagePanel({ channelId, archived }: { channelId: string; archived: boolean }) {
  const messages = useMessages(channelId); const send = useSendMessage(channelId); const markRead = useMarkChannelRead(); const [body, setBody] = useState("");
  useEffect(() => { if (messages.data) markRead.mutate(channelId); }, [channelId, messages.dataUpdatedAt]);
  const submit = (event: FormEvent) => { event.preventDefault(); const value = body.trim(); if (!value || archived || send.isPending) return; send.mutate({ body: value }, { onSuccess: () => setBody("") }); };
  return <section className="flex min-h-[420px] flex-col rounded-xl border border-border bg-surface shadow-sm"><div className="flex items-center justify-between border-b border-border p-4"><span className="font-medium">Conversation</span>{archived && <span className="rounded-full bg-muted px-2 py-1 text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Read-only archive</span>}</div><div className="flex-1 space-y-3 overflow-auto p-4">{messages.isLoading ? <State text="Loading messages…" /> : messages.isError ? <State error text="Messages are unavailable. Retry the conversation." /> : messages.data?.length ? messages.data.map((message) => <div key={message.id} className="rounded-lg border border-border/70 bg-background p-3"><div className="font-mono text-[10px] text-steel">{message.sender_ref} · {new Date(message.created_at).toLocaleString()}</div><p className="mt-1 whitespace-pre-wrap text-sm">{message.body}</p></div>) : <State text="No messages yet. Start the conversation." />}</div>{archived ? <p className="border-t border-border px-4 py-3 text-xs text-muted-foreground">This matter is concluded. Messages remain available for reference, but new posts are disabled.</p> : <>{send.isError && <p role="alert" className="px-3 pt-3 text-xs text-destructive">Unable to send this message. Please retry.</p>}<form onSubmit={submit} className="flex gap-2 border-t border-border p-3"><input value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a message…" aria-label="Message body" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-gold" /><Button type="submit" disabled={send.isPending || !body.trim()}><Send className="mr-2 size-4" />{send.isPending ? "Sending…" : "Send"}</Button></form></>}</section>;
}

function Pins() {
  const pins = usePins(); const remove = useDeletePin(); const create = useCreatePin(); const [resourceType, setResourceType] = useState<string>("CHANNEL"); const [resourceId, setResourceId] = useState(""); const [label, setLabel] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); const id = resourceId.trim(); const name = label.trim(); if (!id || !name || create.isPending) return; create.mutate({ resource_type: resourceType, resource_id: id, label: name }, { onSuccess: () => { setResourceId(""); setLabel(""); } }); };
  if (pins.isLoading) return <State text="Loading saved references…" />; if (pins.isError) return <State error text="Pins are unavailable. Check the API connection and retry." />;
  return <section className="space-y-4"><form onSubmit={submit} className="flex flex-col gap-2 rounded-xl border border-border bg-surface p-4 shadow-sm sm:flex-row sm:flex-wrap"><select value={resourceType} onChange={(event) => setResourceType(event.target.value)} aria-label="Pin resource type" className="rounded-lg border border-border bg-background px-3 py-2 text-sm">{RESOURCE_TYPES.map((type) => <option key={type} value={type}>{type.charAt(0) + type.slice(1).toLowerCase()}</option>)}</select><input value={resourceId} onChange={(event) => setResourceId(event.target.value)} placeholder="Resource UUID" aria-label="Resource UUID" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm" /><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Pin label" aria-label="Pin label" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm" /><Button type="submit" disabled={create.isPending || !resourceId.trim() || !label.trim()}>{create.isPending ? "Saving…" : "Save pin"}</Button></form>{create.isError && <State error text="Unable to save this pin. Confirm the resource UUID and try again." />}{pins.data?.length ? <div className="grid gap-3 md:grid-cols-2">{pins.data.map((pin) => <article key={pin.id} className="flex items-start justify-between rounded-xl border border-border bg-surface p-4 shadow-sm"><div><div className="font-medium">{pin.label}</div><div className="mt-1 font-mono text-[10px] uppercase tracking-widest text-steel">{pin.resource_type} · {pin.resource_id.slice(0, 8)}</div></div><button type="button" aria-label={`Remove ${pin.label}`} onClick={() => remove.mutate(pin.id)} disabled={remove.isPending} className="rounded-md p-2 text-muted-foreground transition-all duration-200 hover:bg-destructive/10 hover:text-destructive"><X className="size-4" /></button></article>)}</div> : <State text="No saved references yet. Pin a channel, thread, or matter when you want it close at hand." />}{remove.isError && <p role="alert" className="text-xs text-destructive">Unable to remove the pin. Please retry.</p>}</section>;
}

function Channels({ chats = false }: { chats?: boolean }) {
  const channels = useChannels(); const createDirect = useCreateDirectChannel(); const [selected, setSelected] = useState<string>(); const [recipient, setRecipient] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); const value = recipient.trim(); if (!value || createDirect.isPending) return; createDirect.mutate(value, { onSuccess: (channel) => { setSelected(channel.id); setRecipient(""); } }); };
  if (channels.isLoading) return <State text="Loading conversations…" />; if (channels.isError) return <State error text="Conversations are unavailable. Check the API connection and retry." />;
  const list = channels.data?.filter((channel) => chats ? channel.kind === "DIRECT" : channel.kind !== "DIRECT") ?? [];
  return (
    <div className="space-y-4">
      {chats && <form onSubmit={submit} className="flex gap-2 rounded-xl border border-border bg-surface p-4 shadow-sm">
        <input value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="Teammate user reference" aria-label="Teammate user reference" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-gold" />
        <Button type="submit" disabled={createDirect.isPending || !recipient.trim()}>{createDirect.isPending ? "Opening…" : <><Plus className="mr-2 size-4" />New chat</>}</Button>
      </form>}
      {createDirect.isError && <State error text="Unable to open that chat. Confirm the teammate reference and try again." />}
      <div className="grid gap-5 lg:grid-cols-[280px_1fr]">
        <section className="space-y-2">
          {list.length ? list.map((channel) => <button type="button" key={channel.id} onClick={() => setSelected(channel.id)} className={`flex w-full items-center gap-3 border-l-2 p-3 text-left transition-all duration-200 ${selected === channel.id ? "border-primary text-[#f3e8c8]" : "border-transparent text-foreground hover:text-white"}`}>
            <Hash className="size-4 text-primary" /><span><strong className="block text-sm">{channel.name}</strong><small className="text-muted-foreground">{channel.is_archived ? "read-only archive" : channel.kind.toLowerCase()}</small></span>
          </button>) : <State text={chats ? "No direct chats yet. Start one above." : "No channels are provisioned for this firm."} />}
        </section>
        {selected ? <MessagePanel channelId={selected} archived={Boolean(list.find((channel) => channel.id === selected)?.is_archived)} /> : <State text="Choose a conversation to read and send messages." />}
      </div>
    </div>
  );
}

function Threads() { const threads = useThreads(); const create = useCreateThread(); const [title, setTitle] = useState(""); return <section className="space-y-4"><form onSubmit={(event) => { event.preventDefault(); const value = title.trim(); if (value && !create.isPending) create.mutate(value, { onSuccess: () => setTitle("") }); }} className="flex gap-2"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="New thread title" aria-label="New thread title" className="flex-1 rounded-lg border border-border bg-surface px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-gold" /><Button type="submit" disabled={create.isPending || !title.trim()}><Plus className="mr-2 size-4" />{create.isPending ? "Creating…" : "New thread"}</Button></form>{create.isError && <State error text="Unable to create the thread. Please retry." />}{threads.isLoading ? <State text="Loading threads…" /> : threads.isError ? <State error text="Threads are unavailable. Check the API connection and retry." /> : threads.data?.length ? <div className="grid gap-3 md:grid-cols-2">{threads.data.map((thread) => <Link key={thread.thread_id} to="/threads/$threadId" params={{ threadId: thread.thread_id }} className="rounded-xl border border-border bg-surface p-4 transition-all duration-200 hover:border-gold/50"><MessageSquare className="size-4 text-gold" /><strong className="mt-3 block">{thread.title}</strong><small className="text-muted-foreground">Updated {new Date(thread.updated_at).toLocaleString()}</small></Link>)}</div> : <State text="No assistant threads yet. Create one to begin grounded work." />}</section>; }

function Contacts() { const members = useMembers(); if (members.isLoading) return <State text="Loading firm directory…" />; if (members.isError) return <State error text="Contacts are unavailable. Check the API connection and retry." />; return members.data?.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{members.data.map((member) => <article key={member.user_ref} className="rounded-xl border border-border bg-surface p-4 shadow-sm"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-gold/15 font-semibold text-gold">{member.full_name.slice(0, 2).toUpperCase()}</span><div><strong className="block">{member.full_name}</strong><small className="text-muted-foreground">{member.role ?? member.clearance ?? "Firm member"}</small></div></div></article>)}</div> : <State text="No firm members found." />; }

export function CollaborationWorkspace({ section }: { section: Section }) { const nav: Section[] = ["pins", "chats", "channels", "threads", "contacts"]; const titles: Record<Section, string> = { pins: "Pins", chats: "DM", channels: "Channels", threads: "Assistant Threads", contacts: "Contacts" }; return <AppShell title={titles[section]} eyebrow={`COMMUNICATIONS · ${section.toUpperCase()}`}><div className="mx-auto max-w-6xl space-y-6"><nav className="flex gap-2 overflow-x-auto border-b border-border pb-3" aria-label="Collaboration sections">{nav.map((item) => <Link key={item} to={`/${item}`} aria-current={item === section ? "page" : undefined} className={`border-l-2 px-3 py-2 text-xs capitalize transition-all duration-200 hover:text-foreground ${item === section ? "border-primary text-[#f3e8c8]" : "border-transparent text-muted-foreground"}`}>{item === "chats" ? "DM" : item}</Link>)}</nav>{section === "pins" && <Pins />}{section === "channels" && <Channels />}{section === "chats" && <Channels chats />}{section === "threads" && <Threads />}{section === "contacts" && <Contacts />}</div></AppShell>; }
