import { Link } from "@tanstack/react-router";
import { Hash, MessageSquare, Plus, Send, Users, X } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { useChannels, useCreatePin, useDeletePin, useMembers, useMessages, usePins, useSendMessage, useThreads, useCreateThread } from "@/lib/api/collaboration";
function MessagePanel({ channelId }: { channelId: string }) { const messages = useMessages(channelId); const send = useSendMessage(channelId); const [body, setBody] = useState(""); return <section className="flex min-h-[420px] flex-col rounded-xl border border-border bg-surface shadow-sm"><div className="border-b border-border p-4 font-medium">Conversation</div><div className="flex-1 space-y-3 overflow-auto p-4">{messages.isLoading ? <State text="Loading messages…" /> : messages.data?.length ? messages.data.map((message) => <div key={message.id} className="rounded-lg border border-border/70 bg-background p-3"><div className="font-mono text-[10px] text-steel">{message.sender_ref} · {new Date(message.created_at).toLocaleString()}</div><p className="mt-1 whitespace-pre-wrap text-sm">{message.body}</p></div>) : <State text="No messages yet. Start the conversation." />}</div><form onSubmit={(event) => { event.preventDefault(); if (!body.trim()) return; send.mutate({ body: body.trim() }); setBody(""); }} className="flex gap-2 border-t border-border p-3"><input value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a message…" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-gold" /><Button type="submit" disabled={send.isPending}><Send className="mr-2 size-4" />Send</Button></form></section>; }
function Threads() { const threads = useThreads(); const create = useCreateThread(); const [title, setTitle] = useState(""); return <section className="space-y-4"><form onSubmit={(e) => { e.preventDefault(); if (title.trim()) { create.mutate(title.trim()); setTitle(""); } }} className="flex gap-2"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="New thread title" className="flex-1 rounded-lg border border-border bg-surface px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-gold" /><Button type="submit"><Plus className="mr-2 size-4" />New thread</Button></form>{threads.isLoading ? <State text="Loading threads…" /> : threads.data?.length ? <div className="grid gap-3 md:grid-cols-2">{threads.data.map((thread) => <Link key={thread.thread_id} to="/threads/$threadId" params={{ threadId: thread.thread_id }} className="rounded-xl border border-border bg-surface p-4 transition-all duration-200 hover:border-gold/50"><MessageSquare className="size-4 text-gold" /><strong className="mt-3 block">{thread.title}</strong><small className="text-muted-foreground">Updated {new Date(thread.updated_at).toLocaleString()}</small></Link>)}</div> : <State text="No assistant threads yet. Create one to begin grounded work." />}</section>; }
function Contacts() { const members = useMembers(); if (members.isLoading) return <State text="Loading firm directory…" />; if (members.isError) return <State text="Contacts are unavailable. Check the API connection and retry." />; return members.data?.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{members.data.map((member) => <article key={member.user_ref} className="rounded-xl border border-border bg-surface p-4 shadow-sm"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-gold/15 font-semibold text-gold">{member.full_name.slice(0, 2).toUpperCase()}</span><div><strong className="block">{member.full_name}</strong><small className="text-muted-foreground">{member.role ?? member.clearance ?? "Firm member"}</small></div></div><div className="mt-4 flex items-center gap-2 text-xs text-steel"><Users className="size-3.5" />Licensed firm member</div></article>)}</div> : <State text="No firm members have been provisioned yet." />; }


type Section = "pins" | "chats" | "channels" | "threads" | "contacts";
const titles: Record<Section, [string, string]> = { pins: ["Pins", "Saved workspace references"], chats: ["Chats", "Direct and recent conversations"], channels: ["Channels", "Firm and matter rooms"], threads: ["Threads", "Your assistant conversations"], contacts: ["Contacts", "Your firm directory"] };
const nav: Section[] = ["pins", "chats", "channels", "threads", "contacts"];
function State({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">{text}</div>; }
export function CollaborationWorkspace({ section }: { section: Section }) { const [title, subtitle] = titles[section]; return <AppShell title={title} eyebrow={`COMMUNICATIONS · ${subtitle.toUpperCase()}`}><div className="mx-auto max-w-6xl space-y-6"><nav className="flex gap-2 overflow-x-auto border-b border-border pb-3">{nav.map((item) => <Link key={item} to={`/${item}`} className={`rounded-lg px-3 py-2 text-xs capitalize transition-all duration-200 hover:bg-surface ${item === section ? "bg-gold/15 text-gold" : "text-muted-foreground"}`}>{item}</Link>)}</nav>{section === "pins" && <Pins />}{section === "channels" && <Channels />}{section === "chats" && <Channels chats />}{section === "threads" && <Threads />}{section === "contacts" && <Contacts />}</div></AppShell>; }
function Pins() { const pins = usePins(); const remove = useDeletePin(); const create = useCreatePin(); const [resourceId, setResourceId] = useState(""); const [label, setLabel] = useState(""); if (pins.isLoading) return <State text="Loading saved references…" />; if (pins.isError) return <State text="Pins are unavailable. Check the API connection and retry." />; return <section className="space-y-4"><form onSubmit={(e) => { e.preventDefault(); if (resourceId.trim() && label.trim()) { create.mutate({ resource_type: "CHANNEL", resource_id: resourceId.trim(), label: label.trim() }); setResourceId(""); setLabel(""); } }} className="flex flex-col gap-2 rounded-xl border border-border bg-surface p-4 sm:flex-row"><input value={resourceId} onChange={(e) => setResourceId(e.target.value)} placeholder="Resource UUID" className="rounded-lg border border-border bg-background px-3 py-2 text-sm" /><input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Pin label" className="rounded-lg border border-border bg-background px-3 py-2 text-sm" /><Button type="submit">Save pin</Button></form>{pins.data?.length ? <div className="grid gap-3 md:grid-cols-2">{pins.data.map((pin) => <article key={pin.id} className="flex items-start justify-between rounded-xl border border-border bg-surface p-4 shadow-sm"><div><div className="font-medium">{pin.label}</div><div className="mt-1 font-mono text-[10px] uppercase tracking-widest text-steel">{pin.resource_type} · {pin.resource_id.slice(0, 8)}</div></div><button type="button" aria-label={`Remove ${pin.label}`} onClick={() => remove.mutate(pin.id)} className="rounded-md p-2 text-muted-foreground transition-all duration-200 hover:bg-destructive/10 hover:text-destructive"><X className="size-4" /></button></article>)}</div> : <State text="No saved references yet. Pin a channel, thread, or matter when you want it close at hand." />}</section>; }
function Channels({ chats = false }: { chats?: boolean }) { const channels = useChannels(); const [selected, setSelected] = useState<string>(); if (channels.isLoading) return <State text="Loading conversations…" />; if (channels.isError) return <State text="Conversations are unavailable. Check the API connection and retry." />; const list = channels.data?.filter((c) => chats ? c.kind === "DIRECT" : c.kind !== "DIRECT") ?? []; return <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><section className="space-y-2">{list.length ? list.map((channel) => <button type="button" key={channel.id} onClick={() => setSelected(channel.id)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition-all duration-200 hover:border-gold/50 ${selected === channel.id ? "border-gold/60 bg-gold/10" : "border-border bg-surface"}`}><Hash className="size-4 text-steel" /><span><strong className="block text-sm">{channel.name}</strong><small className="text-muted-foreground">{channel.kind.toLowerCase()}</small></span></button>) : <State text={chats ? "No direct chats yet." : "No channels are provisioned for this firm."} />}</section>{selected ? <MessagePanel channelId={selected} /> : <State text="Choose a conversation to read and send messages." />}</div>; }
